"use strict";
const DFNSFavorites={
 key:"dfns-favorites", accountKey:"dfns_favorites_v1", api:"https://fortnite-api.com/v2/cosmetics/br/",
 async init(){const root=document.querySelector("#favorites-content");if(!root)return;const account=JSON.parse(localStorage.getItem("dfns_account_v1")||"null");if(!account?.email){this.empty(root,"Sign in to see your favorites.","Your saved cosmetics are connected to your DFNS account.");return}const all=JSON.parse(localStorage.getItem(this.accountKey)||"{}");let ids=Array.isArray(all[account.email])?all[account.email]:[];if(!ids.length){this.empty(root,"No favorites yet.","Open a cosmetic and click Add to Favorites to save it here.");return}document.querySelector("#favorites-count").textContent=`${ids.length} item${ids.length===1?"":"s"}`;root.innerHTML='<div class="favorites-grid" id="favorites-grid"></div>';const grid=document.querySelector("#favorites-grid");const results=await Promise.all(ids.map(id=>this.get(id)));results.forEach((item,i)=>{if(item)this.card(grid,item);else this.card(grid,{id:ids[i],name:"Unknown cosmetic",images:{}})})},
 async get(id){try{const r=await fetch(`${this.api}${encodeURIComponent(id)}?language=en`,{cache:"no-store"});if(!r.ok)return null;const j=await r.json();return j.data||null}catch{return null}},
 card(grid,item){const card=document.createElement("article");card.className="favorite-card";const img=item.images?.featured||item.images?.icon||item.images?.full_background||"";card.innerHTML=`<div class="favorite-card-image">${img?`<img src="${this.escape(img)}" alt="${this.escape(item.name||"")}" loading="lazy">`:""}</div><div class="favorite-card-body"><span class="favorite-card-type">${this.escape(item.type?.displayValue||item.displayType||"Cosmetic")}</span><h2 class="favorite-card-name">${this.escape(item.name||"Unknown cosmetic")}</h2><div class="favorite-card-actions"><a class="favorite-open" href="item.html?id=${encodeURIComponent(item.id)}">View item</a><button class="favorite-remove" type="button" data-remove="${this.escape(item.id)}">Remove</button></div></div>`;card.querySelector("[data-remove]").addEventListener("click",()=>this.remove(item.id,card));grid.appendChild(card)},
 remove(id,card){const account=JSON.parse(localStorage.getItem("dfns_account_v1")||"null");if(!account?.email)return;const all=JSON.parse(localStorage.getItem(this.accountKey)||"{}");all[account.email]=(all[account.email]||[]).filter(x=>x!==id);localStorage.setItem(this.accountKey,JSON.stringify(all));card.remove();const n=document.querySelectorAll(".favorite-card").length;document.querySelector("#favorites-count").textContent=`${n} item${n===1?"":"s"}`;if(!n)this.empty(document.querySelector("#favorites-content"),"No favorites yet.","Your favorites list is empty.")},
 empty(root,title,text){root.innerHTML=`<div class="favorites-empty"><h2>${title}</h2><p>${text}</p></div>`;document.querySelector("#favorites-count").textContent="0 items"},
 escape(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
};document.addEventListener("DOMContentLoaded",()=>DFNSFavorites.init());