"use strict";
const DFNSFavorites={
 key:"dfns-favorites", accountKey:"dfns_favorites_v1", api:"https://fortnite-api.com/v2/cosmetics/br/",
 async init(){const root=document.querySelector("#favorites-content");if(!root)return;window.DFNSFavoritesCore?.sync();const account=JSON.parse(localStorage.getItem("dfns_account_v1")||"null");const all=JSON.parse(localStorage.getItem(this.accountKey)||"{}");let ids=account?.email&&Array.isArray(all[account.email])?all[account.email]:JSON.parse(localStorage.getItem(this.key)||"[]");ids=Array.isArray(ids)?[...new Set(ids.map(String))]:[];if(!ids.length){this.empty(root,"Your favorites are empty.","Add favorites to your list and they’ll all appear here.");return}document.querySelector("#favorites-count").textContent=`${ids.length} item${ids.length===1?"":"s"}`;root.innerHTML='<div class="favorites-grid" id="favorites-grid"></div>';const grid=document.querySelector("#favorites-grid");const results=await Promise.all(ids.map(id=>this.get(id)));results.forEach((item,i)=>this.card(grid,item||{id:ids[i],name:"Unknown cosmetic",images:{}}))},
 async get(id){try{const r=await fetch(`${this.api}${encodeURIComponent(id)}?language=en`,{cache:"no-store"});if(!r.ok)return null;const j=await r.json();return j.data||null}catch{return null}},
 card(grid,item){const card=document.createElement("article");card.className="favorite-card";const img=item.images?.featured||item.images?.icon||item.images?.full_background||"";card.innerHTML=`<div class="favorite-card-image">${img?`<img src="${this.escape(img)}" alt="${this.escape(item.name||"")}" loading="lazy">`:""}</div><div class="favorite-card-body"><span class="favorite-card-type">${this.escape(item.type?.displayValue||item.displayType||"Cosmetic")}</span><h2 class="favorite-card-name">${this.escape(item.name||"Unknown cosmetic")}</h2><div class="favorite-card-actions"><a class="favorite-open" href="item.html?id=${encodeURIComponent(item.id)}">View item</a><button class="favorite-remove" type="button" data-remove="${this.escape(item.id)}">Remove</button></div></div>`;card.querySelector("[data-remove]").addEventListener("click",()=>this.remove(item.id,card));grid.appendChild(card)},
 remove(id,card){const account=JSON.parse(localStorage.getItem("dfns_account_v1")||"null");const all=JSON.parse(localStorage.getItem(this.accountKey)||"{}");const legacy=JSON.parse(localStorage.getItem(this.key)||"[]");if(account?.email){all[account.email]=(all[account.email]||[]).filter(x=>String(x)!==String(id));localStorage.setItem(this.accountKey,JSON.stringify(all))}localStorage.setItem(this.key,JSON.stringify(Array.isArray(legacy)?legacy.filter(x=>String(x)!==String(id)):[]));card.remove();const n=document.querySelectorAll(".favorite-card").length;document.querySelector("#favorites-count").textContent=`${n} item${n===1?"":"s"}`;if(!n)this.empty(document.querySelector("#favorites-content"),"Your favorites are empty.","Add favorites to your list and they’ll all appear here.")},
 empty(root,title,text){root.innerHTML=`<div class="favorites-empty"><h2>${title}</h2><p>${text}</p><a href="shop.html">Browse Item Shop</a></div>`;document.querySelector("#favorites-count").textContent="0 items"},
 escape(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
};document.addEventListener("DOMContentLoaded",()=>DFNSFavorites.init());