(() => {
  const API='https://fortnite-api.com/v1/map';
  const OG_IMAGE='https://www.pcgamesn.com/wp-content/uploads/2019/05/fortnite-season-9-map-1-900x882.jpg';
  const OG_POIS=['Junk Junction','Haunted Hills','Pleasant Park','Snobby Shores','Neo Tilted','Loot Lake','Lazy Lagoon','Pressure Plant','Sunny Steps','Lonely Lodge','Mega Mall','Dusty Divot','Shifty Shafts','Salty Springs','Polar Peak','Frosty Flights','Happy Hamlet','Lucky Landing','Fatal Fields','Paradise Palms'];
  const state={mode:'br',br:null,zoom:1,panX:0,panY:0,dragging:false,lastX:0,lastY:0};const els={};const $=id=>document.getElementById(id);
  function cache(){['map-image','poi-layer','poi-list','poi-count','poi-search','map-name','map-subtitle','map-updated','map-loading','map-refresh','zoom-in','zoom-out','zoom-reset'].forEach(id=>els[id]=$(id))}
  function niceTime(){return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}
  function setUpdated(t){if(els['map-updated'])els['map-updated'].textContent=t}
  function applyTransform(){const t=`translate(${state.panX}px,${state.panY}px) scale(${state.zoom})`;if(els['map-image'])els['map-image'].style.transform=t;if(els['poi-layer'])els['poi-layer'].style.transform=t}
  function resetView(){state.zoom=1;state.panX=0;state.panY=0;applyTransform()}
  function zoomBy(d){state.zoom=Math.max(.85,Math.min(3,state.zoom+d));applyTransform()}
  function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function pois(){if(state.mode==='og')return OG_POIS.map(name=>({name,location:{x:0,y:0}}));return(state.br?.pois||[]).filter(p=>p?.name).sort((a,b)=>a.name.localeCompare(b.name))}
  function renderList(){const q=(els['poi-search']?.value||'').trim().toLowerCase();const list=pois().filter(p=>p.name.toLowerCase().includes(q));els['poi-count'].textContent=list.length;els['poi-list'].innerHTML=list.map(p=>`<button class="poi-row" type="button"><span><strong>${escapeHtml(p.name)}</strong></span><small>POI</small></button>`).join('')||'<div class="poi-row"><span><strong>No locations found</strong></span></div>'}
  function mapPoint(p){const x=Math.max(-120000,Math.min(120000,Number(p.location?.x||0)));const y=Math.max(-120000,Math.min(120000,Number(p.location?.y||0)));return{left:(x+120000)/240000*100,top:(y+120000)/240000*100}}
  function renderMarkers(list){els['poi-layer'].innerHTML=list.map(p=>{const pos=mapPoint(p);return`<span class="map-poi" style="left:${pos.left}%;top:${pos.top}%"><span class="map-poi-dot"></span>${escapeHtml(p.name)}</span>`}).join('')}
  function setMapImage(src,alt){els['map-image'].onload=()=>{els['map-loading'].style.display='none';resetView()};els['map-image'].onerror=()=>{els['map-loading'].innerHTML='<strong>Map image could not be loaded.</strong><small>Try refresh</small>'};els['map-image'].src=src;els['map-image'].alt=alt}
  function useOG(){state.mode='og';els['map-name'].textContent='Fortnite OG — Chapter 1 Season 9';els['map-subtitle'].textContent='The futuristic OG Season 9 island with its classic named locations.';els['map-loading'].style.display='grid';els['map-loading'].innerHTML='<span></span><strong>Loading OG island...</strong>';setMapImage(OG_IMAGE,'Fortnite OG Chapter 1 Season 9 map');els['poi-layer'].innerHTML='';renderList();setUpdated('OG reference · '+niceTime())}
  async function loadBR(force=false){state.mode='br';els['map-name'].textContent='Battle Royale — Current Island';els['map-subtitle'].textContent='Current island map with named locations from live Fortnite map data.';els['map-loading'].style.display='grid';els['map-loading'].innerHTML='<span></span><strong>Loading live island...</strong>';try{const r=await fetch(force?`${API}?t=${Date.now()}`:API,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(!j?.data?.images?.pois)throw new Error('No map image returned');state.br=j.data;setMapImage(j.data.images.pois,'Current Fortnite Battle Royale map');renderMarkers(pois());renderList();setUpdated('Updated '+niceTime())}catch(e){console.error('[DFNS Map]',e);els['map-loading'].innerHTML='<strong>Live map data unavailable</strong><small>Try refresh</small>';renderList()}}
  function switchMode(mode){document.querySelectorAll('.map-mode-tab').forEach(b=>{const a=b.dataset.mapMode===mode;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});resetView();mode==='og'?useOG():loadBR()}
  function bind(){document.querySelectorAll('.map-mode-tab').forEach(b=>b.addEventListener('click',()=>switchMode(b.dataset.mapMode)));els['map-refresh'].addEventListener('click',()=>state.mode==='br'?loadBR(true):useOG());els['poi-search'].addEventListener('input',renderList);els['zoom-in'].addEventListener('click',()=>zoomBy(.2));els['zoom-out'].addEventListener('click',()=>zoomBy(-.2));els['zoom-reset'].addEventListener('click',resetView);const s=$('map-stage');s.addEventListener('wheel',e=>{e.preventDefault();zoomBy(e.deltaY<0?.12:-.12)},{passive:false});s.addEventListener('pointerdown',e=>{state.dragging=true;state.lastX=e.clientX;state.lastY=e.clientY;s.setPointerCapture(e.pointerId)});s.addEventListener('pointermove',e=>{if(!state.dragging)return;state.panX+=e.clientX-state.lastX;state.panY+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;applyTransform()});const end=()=>state.dragging=false;s.addEventListener('pointerup',end);s.addEventListener('pointercancel',end)}
  document.addEventListener('DOMContentLoaded',()=>{cache();bind();switchMode('br');setInterval(()=>{if(state.mode==='br')loadBR(true)},300000)})
})();
