(() => {
  const SOURCE='https://raw.githubusercontent.com/valincius/fn-sprites/main/src/sprites.json';
  const state={items:[],query:'',variant:'all',rarity:'all',sort:'family'};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const pretty=v=>String(v||'base').replace('candy','gummy').replace(/[-_]/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
  const load=async()=>{const grid=$('sprite-grid');grid.innerHTML='<div class="sprite-loading"><span></span><strong>Loading current sprites...</strong></div>';try{const r=await fetch(`${SOURCE}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const data=await r.json();state.items=Array.isArray(data)?data.filter(x=>x&&x.url&&x.parent):[];render();$('sprite-updated').textContent='Live catalog · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch(e){console.error('[DFNS Sprites]',e);grid.innerHTML='<div class="sprite-empty"><strong>Could not load the current sprite catalog.</strong><span>Try Refresh.</span></div>';$('sprite-updated').textContent='Source unavailable'}};
  const filtered=()=>{let a=state.items.filter(x=>(!state.query||`${x.parent} ${x.variant} ${x.rarity}`.toLowerCase().includes(state.query))&& (state.variant==='all'||x.variant===state.variant)&& (state.rarity==='all'||x.rarity===state.rarity));a.sort((x,y)=>{if(state.sort==='rarity')return (y.rarity||'').localeCompare(x.rarity||'');if(state.sort==='variant')return (x.variant||'').localeCompare(y.variant||'');if(state.sort==='id')return Number(x.spriteId)-Number(y.spriteId);return (x.parent||'').localeCompare(y.parent||'')||Number(x.spriteId)-Number(y.spriteId)});return a};
  const render=()=>{const a=filtered(),families=new Set(state.items.map(x=>x.parent)),variants=new Set(state.items.map(x=>x.variant));$('sprite-total').textContent=state.items.length;$('family-total').textContent=families.size;$('variant-total').textContent=variants.size;$('sprite-results').textContent=`${a.length} / ${state.items.length} sprites`;if(!a.length){$('sprite-grid').innerHTML='<div class="sprite-empty"><strong>No sprites found</strong><span>Try another search or filter.</span></div>';return}$('sprite-grid').innerHTML=a.map(x=>`<article class="sprite-card"><div class="sprite-art"><img loading="lazy" src="${esc(x.url)}" alt="${esc(x.parent)} ${esc(x.variant)}" onerror="this.style.opacity='.15'"></div><span class="sprite-variant">${esc(pretty(x.variant))}</span><div class="sprite-info"><div class="sprite-name" title="${esc(x.parent)}">${esc(x.parent)}</div><div class="sprite-meta"><span class="sprite-rarity rarity-${esc(x.rarity)}">${esc(x.rarity)}</span><span class="sprite-id">#${esc(x.spriteId)}</span></div></div></article>`).join('')};
  const bind=()=>{$('sprite-search').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();render()});$('sprite-variant').addEventListener('change',e=>{state.variant=e.target.value;render()});$('sprite-rarity').addEventListener('change',e=>{state.rarity=e.target.value;render()});$('sprite-sort').addEventListener('change',e=>{state.sort=e.target.value;render()});$('sprite-refresh').addEventListener('click',load)};
  document.addEventListener('DOMContentLoaded',()=>{bind();load();setInterval(load,900000)});
})();